name: Moulinette

on:
  issues:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: moulinette

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Moulinette
        uses: ./.github/actions/moulinette
        with:
          github-token: ${{ github.token }}
          github-token-for-private-images: ${{ secrets.MY_GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          issue-extension: '.html.gfm'
      - uses: stefanzweifel/git-auto-commit-action@v5
